language: cpp
dist: bionic
compiler:
   - clang
   
install:
  - sudo apt-get install libomp-dev clang-10
  
script:
  - mkdir build
  - cd build
  - CXX=clang++ cmake ..
  - make
  - ./tsxCount --input=../data/small_t7.1000.fastq --mode=SERIAL --check
  
