version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      # Whatever you want to do
      - run:
          name: "overview"
          command: ls
      - run: sudo apt-get update && sudo apt-get install -y libomp-dev clang-10
      - run:
          name: "Setup Project"
          command: mkdir build && cd build && CXX=clang++ cmake ..
      - run:
          name: "Build Project"
          command: make
      - run:
          name: "Test Project"
          command: ./tsxCount --input=../data/small_t7.1000.fastq --mode=SERIAL --check
