version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Install Deps"
          command: sudo apt-get install libomp-dev clang-10
      - run:
          name: "Setup Project"
          command: mkdir build && cd build && CXX=clang++ cmake ..
      - run:
          name: "Build Project"
          command: make
      - run:
          name: "Test Project"
          command: ./tsxCount --input=../data/small_t7.1000.fastq --mode=SERIAL --check
