version: 2.1

jobs:
  build:
    docker:
      image: 'clangbuiltlinux/ubuntu'
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Install Deps"
          command: sudo apt-get update && sudo apt-get install libomp-dev
      - run:
          name: "Setup Project"
          command: mkdir build && cd build && CXX=clang++ cmake ..
      - run:
          name: "Build Project"
          command: make
      - run:
          name: "Test Project"
          command: ./tsxCount --input=../data/small_t7.1000.fastq --mode=SERIAL --check
