version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      # Whatever you want to do
      - run:
          name: "overview"
          command: ls && pwd
      - run:
          name: "Install Deps"
          command: sudo apt-get update && sudo apt-get install -y libomp-dev clang-10 cmake zlib1g-dev
      - run:
          name: "Check Tools"
          command: which cmake clang++-10
      - run:
          name: "Setup Project"
          command: mkdir build && cd build && CXX=clang++-10 cmake ..
      - run:
          name: "Build Project"
          command: cd build && make
      - run:
          name: "Test Project"
          command: ./build/tsxCount --input=./data/small_t7.1000.fastq --mode=SERIAL --check
